#!/bin/sh

set -e 


if [ "$1" = "purge" ] ; then
      if [ -d /etc/oss4 ]; then
         rm -rf /etc/oss4
      fi
      if [ -d /var/lib/oss4 ]; then
         rm -rf /etc/oss4
      fi
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/oss4-base" ] ; then
	chmod -x "/etc/init.d/oss4-base" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d oss4-base remove >/dev/null
fi
# End automatically added section


exit 0
