#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/oss4-base" ]; then
		update-rc.d oss4-base start 50 S . stop 50 0 1 6 . >/dev/null || exit 1
	fi
fi
# End automatically added section
