#! /bin/sh
# postinst script for liquidsoap
set -e

#DEBHELPER#

case "$1" in
    configure)
        # Restart oss4-base
	if command -v invoke-rc.d >/dev/null 2>&1; then
		invoke-rc.d oss4-base force-reload
	else
		/etc/init.d/oss4-base force-reload
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
    ;;

    *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0

