# Open Sound System configuration file
# Remove the '#' in front of the option(s) you like to set.
#
# 
# lynxtwo_init_order determines if the output devices files are created before
# the input ones (0) or vice versa (1).
# 
# This may be necessary with a known application which expect all /dev/dsp#
# devices to be recording devices.
# 
#lynxtwo_init_order=0
