# Open Sound System configuration file
# Remove the '#' in front of the option(s) you like to set.
#
# 
# audioloop_instances: Number of instances (client/server pairs) to create.
# 
#audioloop_instances=1
