# Open Sound System configuration file
# Remove the '#' in front of the option(s) you like to set.
#
# 
# midiloop_instances gives the number of MIDI loopback devices to be created.
# The default value is 1
# 
#midiloop_instances = 1
