# Open Sound System configuration file
# Remove the '#' in front of the option(s) you like to set.
#
# 
# IMUX supports multiple instances, please consult the man page
# 
# 
# 
# Number of IMUX client side devices to configure. 
# Values: 2-48    Default: 5.
# 
# 
#imux_devices=5
#
# 
# Master physical device to use (ie attach IMUX to a specific soundcard)
# -1 means automatically detect the device. Use the device index numbers
# reported by ossinfo -a.
# Values: 0-N 	Default: -1 (autodetect)
# 
# 
#imux_masterdev=-1
#
# 
# Select the base sampling rate for the IMUX device. The base rate must be
# one supported by the actual physical device (as reported by audioinfo -a -v2).
# Values: 8000-192000	Default: 48000
# 
#imux_rate=48000
