#! /bin/sh
# postinst script for liquidsoap
set -e

# Automatically added by dh_dkms/3.2.2-1~deb13u1
DKMS_NAME=oss4
DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
DKMS_VERSION=4.2-build2020

postinst_found=0

case "$1" in
	configure)
		for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
			if [ -f $DKMS_POSTINST ]; then
				$DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
				postinst_found=1
				break
			fi
		done
		if [ "$postinst_found" -eq 0 ]; then
			echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
			echo "built with legacy DKMS support."
			echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
			echo "support or upgrade DKMS to a more current version."
			exit 1
		fi
	;;
esac
# End automatically added section


case "$1" in
    configure)
        # Restart oss4-base
	if command -v invoke-rc.d >/dev/null 2>&1; then
		invoke-rc.d oss4-base force-reload
	else
		/etc/init.d/oss4-base force-reload
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
    ;;

    *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0

