#!/bin/sh
set -e
# Automatically added by dh_dkms/3.2.2-1~deb13u1
DKMS_NAME=oss4
DKMS_VERSION=4.2-build2020

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
