/*
 * Automatically generated by the configure script (srcconf.c) - Do not edit.
*/
#define CONFIG_OSS_GRC_MIN_QUALITY 3
#define CONFIG_OSS_GRC_MAX_QUALITY 3
#define CONFIG_OSS_VMIX
#undef  CONFIG_OSS_VMIX_FLOAT
#define CONFIG_OSS_MIDI
#define OSS_CONFIG_OPTIONS "--enable-libsalsa=NO --config-vmix=FIXEDPOINT"
